# Generated by Django 5.1.3 on 2024-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=2000, verbose_name='Вес товара'),
            preserve_default=False,
        ),
    ]
