# Generated by Django 5.1.4 on 2024-12-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
