# Generated by Django 5.1.3 on 2024-12-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_modelauto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.modelauto', verbose_name='Модель авто'),
        ),
        migrations.AlterModelOptions(
            name='modelauto',
            options={'verbose_name': 'Модель авто', 'verbose_name_plural': 'Модели авто'},
        ),
        migrations.DeleteModel(
            name='ModelProduct',
        ),
    ]
