# Generated by Django 5.1.4 on 2024-12-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=2, max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=25, verbose_name='Артикул'),
        ),
    ]
