# Generated by Django 5.1.4 on 2024-12-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_model_alter_modelauto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
